// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdttfosbledjbiqrutsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdHRmb3NibGVkamJpcXJ1dHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjkwNTQsImV4cCI6MjA1Mjk0NTA1NH0.fSSi3WQkL2GtzteSKiBjKlkKGpO7IKHavZ6YVnb7TP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);